export enum ERROR_CODES {
  INVALID_REQUEST = 'INVALID_REQUEST',
  INVALID_PARAMS = 'INVALID_PARAMS',

  INVALID_TOKEN = 'INVALID_TOKEN',

  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // For quiz API
  QUIZ_NOT_FOUND = 'QUIZ_NOT_FOUND',
  ALREADY_SUBMITTED_QUIZ = 'ALREADY_SUBMITTED_QUIZ',
  NOT_ENOUGH_ANSWERS = 'NOT_ENOUGH_ANSWERS',
}

export const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_TOKEN]: 'INVALID_TOKEN',
  [ERROR_CODES.INVALID_PARAMS]: 'INVALID_PARAMS',
  [ERROR_CODES.NOT_FOUND]: 'NOT_FOUND',
  [ERROR_CODES.FORBIDDEN]: 'FORBIDDEN',
  [ERROR_CODES.UNAUTHORIZED]: 'UNAUTHORIZED',
  [ERROR_CODES.INVALID_REQUEST]: 'INVALID_REQUEST',

  [ERROR_CODES.QUIZ_NOT_FOUND]: 'QUIZ_NOT_FOUND',
  [ERROR_CODES.ALREADY_SUBMITTED_QUIZ]: 'ALREADY_SUBMITTED_QUIZ',
  [ERROR_CODES.NOT_ENOUGH_ANSWERS]: 'NOT_ENOUGH_ANSWERS',
};

export function getErorrMessage(errorCode: ERROR_CODES): string {
  return ERROR_MESSAGES[errorCode] || 'UNKNOWN_ERROR';
}
